#!/bin/python3

import math
import os
import random
import re
import sys


#
# Complete the 'filledOrders' function below.
#
# The function is expected to return an INTEGER.
# The function accepts following parameters:
#  1. INTEGER_ARRAY order
#  2. INTEGER k
#

def filledOrders(order, k):
    # Write your code here
    total=k;
    fulf=[]
    for r in order:
        if r<=total:
            fulf.append(r)
            total-=r
        else:
            break;
    if sum(fulf)>k:
            fulf.pop
    return len(fulf)

if __name__ == '__main__':
